name       : opensp
version    : 1.5.2
release    : 3
source     :
    - http://freefr.dl.sourceforge.net/project/openjade/opensp/1.5.2/OpenSP-1.5.2.tar.gz : 57f4898498a368918b0d49c826aa434bb5b703d2c3b169beb348016ab25617ce
license    : MIT
component  : programming
summary    : A library and a set of tools for validating, parsing and manipulating SGML and XML documents
description: |
    A library and a set of tools for validating, parsing and manipulating SGML and XML documents
builddeps  :
    - docbook-xml
    - xmlto
setup      : |
    %configure --disable-static \
        --enable-http \
        --enable-default-catalog=/etc/sgml/catalog:/etc/xml/catalog \
        --enable-default-search-path=/usr/share/sgml:/usr/share/xml \
        --enable-xml-messages
build      : |
    %make
install    : |
    %make_install
